name: ojo
favicon: null
layout_spectrum: 0.04498456185683608
typography_spectrum: 0.2280123340897262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0702766478061676
  lightness: 0.9717605623882264
  saturation: 0.7796642628964037
  rhythmicContrast: 0.5927842077799141
purpose: []
