name: ojo
favicon: null
layout_spectrum: 0.04498456185683608
typography_spectrum: 0.2280123340897262
title: ojo services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#41114d'
    - '#9f88a6'
    - '#b2b5b9'
    - '#facb99'
  brandStrength: 1
  lightness: 0.9717605623882264
  saturation: 0.7796642628964037
  rhythmicContrast: 0.5927842077799141
purpose: []
